services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: dbt
      POSTGRES_DB: dbt_db
    ports:
      - "5432:5432"   # optional but useful for local access

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    volumes:
      - .:/usr/app
      - ./profiles.yml:/root/.dbt/profiles.yml
    working_dir: /usr/app

  superset:
    image: apache/superset:latest
    container_name: superset
    depends_on:
      - postgres
    build: .
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "dev_key"
    volumes:
      - superset_home:/app/superset_home

volumes:
  superset_home: