acidentes_projeto:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: dbt
      password: dbt
      port: 5432
      dbname: dbt_db
      schema: public
      threads: 2